/** Synthetic additive P1 contracts. No permanent record/file purge or external service. */
import '../tests/helpers/bootstrap';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {readFile,readdir} from 'node:fs/promises';
import {Miniflare} from 'miniflare';
import type {D1Database} from '@cloudflare/workers-types';
import {runWithHostedBindings} from '../src/shared/server/hosted-runtime/index.server';
const mf=new Miniflare({cf:false,modules:true,script:"export default {fetch(){return new Response('fixture')}}",compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:{DB:'p1-contracts'}});
let checks=0;const check=(value:unknown,label:string)=>{assert.ok(value,label);checks++;console.log('PASS '+label);};
try {
 const DB=await mf.getD1Database('DB') as unknown as D1Database;
 for(const file of (await readdir('drizzle')).filter(f=>f.endsWith('.sql')).sort())for(const sql of (await readFile('drizzle/'+file,'utf8')).split('--> statement-breakpoint').map(s=>s.trim()).filter(Boolean))await DB.prepare(sql).run();
 await runWithHostedBindings({DB},async()=>{
  const {getDatabasePool}=await import('../src/shared/server/database/index.server');const db=getDatabasePool();
  const {createTask,getTaskById,setTaskPredecessors,getDependencySnapshot,changeTaskStatus}=await import('../src/entities/task/index.server');
  const {createSubmission}=await import('../src/entities/submission/index.server');
  for(const [id,role]of [[1,'guest'],[2,'member'],[3,'member'],[4,'admin']] as const)await db.query('INSERT INTO users(id,email,name,role) VALUES(?,?,?,?)',[id,`p1-${id}@example.test`,`P1 ${id}`,role]);
  for(const id of [1,2])await db.query("INSERT INTO projects(id,name,start_date,end_date) VALUES(?,?,'2026-01-01','2026-12-31')",[id,`P1 ${id}`]);
  const actor={userId:2,isAdmin:false,isSuperuser:false};
  const make=(title:string,projectId=1)=>createTask({projectId,title,actor,token:randomUUID(),assigneeId:2,startDate:'2026-01-01',endDate:'2026-12-31',deliverable:'output',definitionOfDone:'check'});
  const a=await make('A'),b=await make('B'),c=await make('C'),foreign=await make('Other',2);
  async function edge(taskId:number,predecessorIds:number[],token=randomUUID()) {return setTaskPredecessors({taskId,predecessorIds,actor,token,version:(await getTaskById(taskId))!.version,graphVersion:(await getDependencySnapshot(1)).version});}
  const snap=await getDependencySnapshot(1),initial={taskId:b.id,predecessorIds:[a.id],actor,token:randomUUID(),version:b.version,graphVersion:snap.version};
  await Promise.all([setTaskPredecessors(initial),setTaskPredecessors(initial)]);
  check((await getDependencySnapshot(1)).edges.length===1,'same request adds one edge');
  check(Number((await db.query('SELECT COUNT(*) n FROM task_events WHERE kind=?',['dependencies_changed']) as {n:number}[])[0].n)===1,'same request adds one history');
  await assert.rejects(setTaskPredecessors({...initial,predecessorIds:[c.id]}));checks++;
  await assert.rejects(edge(a.id,[b.id]),/순환/);checks++;
  await assert.rejects(edge(c.id,[foreign.id]),/같은 프로젝트/);checks++;
  await assert.rejects(edge(c.id,[c.id]));checks++;
  await assert.rejects(setTaskPredecessors({...initial,taskId:c.id,actor:{...actor,userId:1},token:randomUUID()}));checks++;
  async function status(taskId:number,status:'planned'|'in_progress'|'done',note='synthetic transition'){await changeTaskStatus({id:taskId,status,note,actor,token:randomUUID(),version:(await getTaskById(taskId))!.version});}
  await assert.rejects(status(b.id,'in_progress'),/선행/);checks++;
  await createSubmission({actor,token:randomUUID(),taskId:a.id,authorId:2,content:'evidence'});
  await status(a.id,'done');await status(b.id,'in_progress');check((await getTaskById(b.id))!.status==='in_progress','completion enables successor start');
  await assert.rejects(edge(b.id,[]),/예정/);checks++;
  await status(a.id,'in_progress');await assert.rejects(status(b.id,'done'),/선행/);checks++;
  check((await getTaskById(b.id))!.status==='in_progress','predecessor reopen preserves successor status');
  const d=await make('D'),e=await make('E'),graph=(await getDependencySnapshot(1)).version;
  const reverse=await Promise.allSettled([setTaskPredecessors({taskId:d.id,predecessorIds:[e.id],version:d.version,graphVersion:graph,actor,token:randomUUID()}),setTaskPredecessors({taskId:e.id,predecessorIds:[d.id],version:e.version,graphVersion:graph,actor,token:randomUUID()})]);
  check(reverse.filter(result=>result.status==='fulfilled').length===1,'concurrent reverse edges allow one graph version');
  const review=await createTask({projectId:1,title:'Review dependency',actor,token:randomUUID(),assigneeId:2,reviewRequired:true,deliverable:'output',definitionOfDone:'verify',startDate:'2026-01-01',endDate:'2026-12-31'});
  const {updateTask}=await import('../src/entities/task/index.server');
  await updateTask({...review,id:review.id,actor,token:randomUUID(),version:review.version,reviewerId:3});
  await edge(review.id,[a.id]);
  const output=await createSubmission({actor,token:randomUUID(),taskId:review.id,authorId:2,content:'review output'});
  const {requestSubmissionReview,decideSubmissionReview,cancelOrReopenSubmissionReview}=await import('../src/entities/submission/index.server');
  const reviewInput=async()=>({taskId:review.id,submissionId:output.id,revisionNumber:1,expectedTaskVersion:(await getTaskById(review.id))!.version,actor,token:randomUUID()});
  await assert.rejects(requestSubmissionReview(await reviewInput()),/선행/);checks++;
  await status(a.id,'done');await requestSubmissionReview(await reviewInput());
  check((await getTaskById(review.id))!.status==='review_pending','complete predecessor enables review');
  await status(a.id,'in_progress');
  await assert.rejects(decideSubmissionReview({...await reviewInput(),actor:{...actor,userId:3},decision:'approved',reason:'checked'}),/선행/);checks++;
  await cancelOrReopenSubmissionReview({...await reviewInput(),reason:'cancel blocked review'});
  check((await getTaskById(review.id))!.status==='in_progress','blocked review can be cancelled without losing history');
  const fault=await make('Dependency fault'),faultGraph=await getDependencySnapshot(1);
  await DB.prepare("CREATE TRIGGER dependency_history_fault BEFORE INSERT ON task_events WHEN NEW.task_id="+fault.id+" AND NEW.kind='dependencies_changed' BEGIN SELECT RAISE(ABORT,'synthetic dependency history fault'); END").run();
  await assert.rejects(edge(fault.id,[a.id]));checks++;
  check((await getTaskById(fault.id))!.version===fault.version&&(await getDependencySnapshot(1)).version===faultGraph.version,'history failure rolls back graph CAS and task version');
  check(!(await getDependencySnapshot(1)).edges.some(e=>e.taskId===fault.id),'history failure leaves no partial edges');
  const {applyTaskTemplate}=await import('../src/entities/task/index.server');
  const {taskTemplates,templatePreview}=await import('../src/entities/task');
  const template=taskTemplates[0],nodes=templatePreview(template,'2026-01-01');nodes[0].assigneeId=2;nodes[0].title='CUSTOM TEMPLATE';
  const templateInput={projectId:1,templateKey:template.key,templateVersion:template.version,nodes,actor,token:randomUUID()};
  const copies=await Promise.all([applyTaskTemplate(templateInput),applyTaskTemplate(templateInput)]);
  check(JSON.stringify(copies[0].taskIds)===JSON.stringify(copies[1].taskIds)&&copies[0].taskIds.length===4,'template concurrent replay returns one hierarchy');
  const child=await getTaskById(copies[0].taskIds[1]);check(child?.parentId===copies[0].taskIds[0]&&child.depth===1,'template parent-first hierarchy and depth');
  const root=await getTaskById(copies[0].taskIds[0]);check(root?.title==='CUSTOM TEMPLATE'&&root.assigneeId===2&&root.status==='planned'&&!root.reviewRequired,'template custom fields persist without automatic review');
  const templatesBefore=Number((await db.query('SELECT COUNT(*) n FROM task_template_runs') as {n:number}[])[0].n);
  await assert.rejects(applyTaskTemplate({...templateInput,nodes:[{...nodes[0],title:'changed'}]}));checks++;
  await assert.rejects(applyTaskTemplate({...templateInput,token:randomUUID(),nodes:[{...nodes[0],assigneeId:1}]}));checks++;
  await assert.rejects(applyTaskTemplate({...templateInput,actor:{...actor,userId:1},token:randomUUID()}));checks++;
  check(Number((await db.query('SELECT COUNT(*) n FROM task_template_runs') as {n:number}[])[0].n)===templatesBefore,'invalid role/assignee leaves no application receipt');
  await DB.prepare("CREATE TRIGGER template_history_fault BEFORE INSERT ON task_events WHEN NEW.task_id IN (SELECT id FROM tasks WHERE title='TEMPLATE_FAULT') BEGIN SELECT RAISE(ABORT,'template history fault'); END").run();
  const failedTemplateToken=randomUUID();
  await assert.rejects(applyTaskTemplate({...templateInput,token:failedTemplateToken,nodes:[nodes[0],{...nodes[1],title:'TEMPLATE_FAULT'}]}));checks++;
  const failedPrefix=actor.userId+':template:'+failedTemplateToken;
  check(Number((await db.query('SELECT COUNT(*) n FROM tasks WHERE creation_token IN (?,?)',[failedPrefix+':'+nodes[0].key,failedPrefix+':'+nodes[1].key]) as {n:number}[])[0].n)===0&&Number((await db.query('SELECT COUNT(*) n FROM task_events WHERE operation_token IN (?,?)',[failedPrefix+':'+nodes[0].key,failedPrefix+':'+nodes[1].key]) as {n:number}[])[0].n)===0,'late template failure rolls back first card and its event too');
  check(Number((await db.query('SELECT COUNT(*) n FROM task_template_runs') as {n:number}[])[0].n)===templatesBefore,'late template failure rolls back receipt and every card');
  check(!(await db.query("SELECT id FROM tasks WHERE title='TEMPLATE_FAULT'") as {id:number}[]).length,'late template failure preserves no partial hierarchy');
  const {searchWork}=await import('../src/entities/task/index.server');
  const {parseWorkSearchFilters}=await import('../src/entities/task');
  const {commitSubmissionRevision}=await import('../src/entities/submission/api/submission-revision.server');
  const secret=await createSubmission({actor,token:randomUUID(),taskId:a.id,authorId:2,content:'P1_SECRET_ORIGINAL',visibility:'private'});
  await commitSubmissionRevision({id:secret.id,actor,token:randomUUID(),expectedRevision:1,content:'P1_SEARCH_VISIBLE',visibility:'public',changeSummary:'public copy'},[]);
  const search=(id:number,q:string,extra:Record<string,string>={})=>searchWork({viewerUserId:id,isSuperuser:false},parseWorkSearchFilters({q,kind:'submission',versions:'all',...extra}));
  check((await search(3,'P1_SECRET_ORIGINAL')).total===0,'search hides formerly private historical body from other member');
  check((await search(2,'P1_SECRET_ORIGINAL')).total===1&&(await search(4,'P1_SECRET_ORIGINAL')).total===1,'search owner/admin sees permitted private history');
  check((await search(1,'P1_SEARCH_VISIBLE')).total===1,'search guest sees current public version');
  await db.query("INSERT INTO submission_attachments(submission_id,revision_number,file_path,file_name,file_size_bytes) VALUES(?,1,'fixture/private','SECRET_FILENAME',1)",[secret.id]);
  check((await search(3,'SECRET_FILENAME')).total===0&&(await search(2,'SECRET_FILENAME')).total===1,'filename matching respects historical visibility before count');
  await commitSubmissionRevision({id:secret.id,actor,token:randomUUID(),expectedRevision:2,content:'P1_SECRET_CURRENT',visibility:'private',changeSummary:'make private'},[]);
  check((await search(3,'P1_SEARCH_VISIBLE')).total===0,'current private boundary hides former public history');
  await db.query("UPDATE users SET role='guest' WHERE id=4");
  check((await search(4,'P1_SECRET_ORIGINAL')).total===0,'search rereads downgraded admin role');
  await db.query("UPDATE users SET role='admin' WHERE id=4");
  const literal=await createSubmission({actor,token:randomUUID(),taskId:a.id,authorId:2,content:'P1 literal 50%_!',visibility:'public'});
  check((await search(3,'50%_!')).total===1&&(await search(3,'50%_!')).items[0].id===literal.id,'search wildcard punctuation is literal');
  for(let i=0;i<22;i++)await createSubmission({actor,token:randomUUID(),taskId:a.id,authorId:2,content:'P1_PAGE_MARKER '+i,visibility:i<21?'public':'private'});
  const page1=await search(3,'P1_PAGE_MARKER'),page2=await search(3,'P1_PAGE_MARKER',{page:'2'});
  check(page1.total===21&&page1.items.length===20&&page2.items.length===1&&page2.total===21,'pagination counts only visible versions');
  const p1Submission=page1.items[0];
  await db.query("INSERT INTO submission_attachments(submission_id,revision_number,file_path,file_name,file_size_bytes) VALUES(?,1,'fixture/a','P1_DUP_FILE',1),(?,1,'fixture/b','P1_DUP_FILE',1)",[p1Submission.id,p1Submission.id]);
  check((await search(3,'P1_DUP_FILE')).total===1,'multiple matching filenames do not duplicate search rows');
  check((await search(3,'P1_PAGE_MARKER',{projectId:'2'})).total===0,'project filter applies before count');
  check((await search(3,'P1_PAGE_MARKER',{versions:'approved'})).total===0,'ordinary submitted content is not mislabeled approved');
  await status(a.id,'done');await requestSubmissionReview(await reviewInput());await decideSubmissionReview({...await reviewInput(),actor:{...actor,userId:3},decision:'approved',reason:'checked'});
  check((await search(3,'review output',{versions:'approved'})).total===1,'search includes current exact approved revision');
  await cancelOrReopenSubmissionReview({...await reviewInput(),reason:'recheck'});
  check((await search(3,'review output',{versions:'approved'})).total===0&&(await search(3,'review output',{versions:'all'})).total===1,'revoked approval leaves ordinary history but not approved search');
  const history=await db.query('SELECT t.id,t.version,COUNT(e.id) n FROM tasks t LEFT JOIN task_events e ON e.task_id=t.id GROUP BY t.id,t.version') as {version:number;n:number}[];
  check(history.every(row=>Number(row.version)===Number(row.n)),'task state/history atomicity preserved');
 });
 console.log(`P1 contracts: ${checks} PASS`);
}finally{await mf.dispose();}
